# Generated by Django 5.2.6 on 2026-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="slot",
        ),
        migrations.AddField(
            model_name="booking",
            name="slots",
            field=models.ManyToManyField(
                related_name="bookings_as_slot", to="app.slot"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="required_slot",
            field=models.IntegerField(default=1),
        ),
    ]
